name: Build on Push

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14' # or the version you need

    - name: Install Dependencies
      run: npm install

    - name: Run Build
      run: npm run build
